"""add public with link to visibility

Revision ID: 115cd01a3045
Revises: f56beb654c97
Create Date: 2026-08-06 15:51:19.941587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '115cd01a3045'
down_revision: Union[str, Sequence[str], None] = 'f56beb654c97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='visibility',
        new_values=['PUBLIC', 'PRIVATE', 'PUBLIC_WITH_LINK'],
        affected_columns=[TableReference(table_schema='public', table_name='quizzes', column_name='visibility')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='visibility',
        new_values=['PUBLIC', 'PRIVATE'],
        affected_columns=[TableReference(table_schema='public', table_name='quizzes', column_name='visibility')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
