"""add allow_negative_score in quiz

Revision ID: 2d8da3d66f85
Revises: 934be6ca5494
Create Date: 2026-08-02 15:17:44.724238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d8da3d66f85'
down_revision: Union[str, Sequence[str], None] = '934be6ca5494'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('allow_negative_score', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'allow_negative_score')
    # ### end Alembic commands ###
