"""add randomize questions and answers to quiz

Revision ID: 2dbce1a55746
Revises: 8049aaebff08
Create Date: 2026-08-11 22:37:57.224511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dbce1a55746'
down_revision: Union[str, Sequence[str], None] = '8049aaebff08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('randomize_questions', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('quizzes', sa.Column('randomize_answers', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'randomize_answers')
    op.drop_column('quizzes', 'randomize_questions')
    # ### end Alembic commands ###
