"""remove questions and answers tables

Revision ID: 661db374b705
Revises: e63cdbbdb289
Create Date: 2026-07-27 17:40:24.347612

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "661db374b705"
down_revision: Union[str, Sequence[str], None] = "e63cdbbdb289"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_answer_options_question_id"), table_name="answer_options")
    op.drop_table("answer_options")
    op.drop_index(op.f("ix_questions_quiz_id"), table_name="questions")
    op.drop_index(op.f("ix_questions_type"), table_name="questions")
    op.drop_table("questions")
    op.add_column(
        "quizzes",
        sa.Column("questions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    sa.Enum("MCQ", "TRUE_OR_FALSE", name="questiontype").drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("MCQ", "TRUE_OR_FALSE", name="questiontype").create(op.get_bind())
    op.drop_column("quizzes", "questions")
    op.create_table(
        "questions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("quiz_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("text", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM(
                "MCQ", "TRUE_OR_FALSE", name="questiontype", create_type=False
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("position", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["quiz_id"],
            ["quizzes.id"],
            name=op.f("questions_quiz_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("questions_pkey")),
    )
    op.create_index(op.f("ix_questions_type"), "questions", ["type"], unique=False)
    op.create_index(
        op.f("ix_questions_quiz_id"), "questions", ["quiz_id"], unique=False
    )
    op.create_table(
        "answer_options",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("question_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("text", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("is_correct", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("answer_options_question_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("answer_options_pkey")),
    )
    op.create_index(
        op.f("ix_answer_options_question_id"),
        "answer_options",
        ["question_id"],
        unique=False,
    )
    # ### end Alembic commands ###
