"""add grade tiers

Revision ID: 8049aaebff08
Revises: 115cd01a3045
Create Date: 2026-08-11 19:21:24.324934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8049aaebff08'
down_revision: Union[str, Sequence[str], None] = '115cd01a3045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempts', sa.Column('grade', sa.String(length=20), nullable=True))
    op.add_column('quizzes', sa.Column('grade_tiers', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'grade_tiers')
    op.drop_column('attempts', 'grade')
    # ### end Alembic commands ###
