"""make quiz id nullable in attempts table

Revision ID: 934be6ca5494
Revises: 6f49908ef287
Create Date: 2026-07-28 17:34:45.096314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '934be6ca5494'
down_revision: Union[str, Sequence[str], None] = '6f49908ef287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attempts', 'quiz_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attempts', 'quiz_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
