"""questions table

Revision ID: a8fec3315027
Revises: ade1dd84585f
Create Date: 2026-07-26 17:12:45.116804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8fec3315027'
down_revision: Union[str, Sequence[str], None] = 'ade1dd84585f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('MCQ', 'TRUE_OR_FALSE', name='questiontype').create(op.get_bind())
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('type', postgresql.ENUM('MCQ', 'TRUE_OR_FALSE', name='questiontype', create_type=False), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_quiz_id'), 'questions', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_questions_type'), 'questions', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_type'), table_name='questions')
    op.drop_index(op.f('ix_questions_quiz_id'), table_name='questions')
    op.drop_table('questions')
    sa.Enum('MCQ', 'TRUE_OR_FALSE', name='questiontype').drop(op.get_bind())
    # ### end Alembic commands ###
