"""add quiz access

Revision ID: f56beb654c97
Revises: 2d8da3d66f85
Create Date: 2026-08-02 23:16:05.185497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'f56beb654c97'
down_revision: Union[str, Sequence[str], None] = '2d8da3d66f85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('granted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quiz_id', 'user_id', name='uq_quiz_access_quiz_user')
    )
    op.create_index(op.f('ix_quiz_access_granted_by'), 'quiz_access', ['granted_by'], unique=False)
    op.create_index(op.f('ix_quiz_access_quiz_id'), 'quiz_access', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_access_user_id'), 'quiz_access', ['user_id'], unique=False)
    op.sync_enum_values(
        enum_schema='public',
        enum_name='visibility',
        new_values=['PUBLIC', 'PRIVATE'],
        affected_columns=[TableReference(table_schema='public', table_name='quizzes', column_name='visibility')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='visibility',
        new_values=['PUBLIC'],
        affected_columns=[TableReference(table_schema='public', table_name='quizzes', column_name='visibility')],
        enum_values_to_rename=[],
    )
    op.drop_index(op.f('ix_quiz_access_user_id'), table_name='quiz_access')
    op.drop_index(op.f('ix_quiz_access_quiz_id'), table_name='quiz_access')
    op.drop_index(op.f('ix_quiz_access_granted_by'), table_name='quiz_access')
    op.drop_table('quiz_access')
    # ### end Alembic commands ###
